# Generated by Django 2.1.7 on 2020-11-16 06:03

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='更新修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('image_url', models.URLField(verbose_name='轮播图url')),
                ('priority', models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级'), (4, '第四级'), (5, '第五级'), (6, '第六级')], default=6, verbose_name='轮播图优先级')),
            ],
            options={
                'verbose_name': '轮播图',
                'db_table': 'tb_banner',
                'ordering': ['-mod', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.random, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
