# Generated by Django 2.1.7 on 2020-11-17 12:10

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201116_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='digest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.random, max_length=12, primary_key=True, serialize=False),
        ),
    ]
